package it.isislab.masonhelperdocumentation.ODD;

import java.io.Serializable;

/**
 * This class represent a variable;
 * It is used for describe Entity.
 * @author Romano Simone 0512101343
 *
 */
public class Variable implements Serializable{
	private static final long serialVersionUID = 1;
	private String name, userComment, autoGeneratedComment, initialValue;

	public Variable(String name, String userComment, String autoGeneratedComment, String initialValue) {
		super();
		this.name = name;
		this.userComment = userComment;
		this.initialValue = initialValue;
		this.autoGeneratedComment = autoGeneratedComment;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInitialValue() {
		return initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

	public String getUserComment() {
		if (userComment == null) return "";
		return userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

	public String getAutoGeneratedComment() {
		return autoGeneratedComment;
	}

	public void setAutoGeneratedComment(String autoGeneratedComment) {
		this.autoGeneratedComment = autoGeneratedComment;
	}
	
	
}
