package it.isislab.masonhelperdocumentation.mason.wizards;

import it.isislab.masonhelperdocumentation.ODD.ODD;
import it.isislab.masonhelperdocumentation.ODD.ProcessOverviewElement;
import it.isislab.masonhelperdocumentation.analizer.AgentAnalizer;
import it.isislab.masonhelperdocumentation.analizer.GlobalUtility;
import it.isislab.masonhelperdocumentation.analizer.Method;
import it.isislab.masonhelperdocumentation.analizer.SimStateAnalizer;
import it.isislab.masonhelperdocumentation.mason.wizards.MASONDocumentationWizard;

import java.util.ArrayList;
import java.util.logging.Logger;

import org.eclipse.jface.wizard.IWizardPage;
import org.eclipse.jface.wizard.Wizard;
import org.eclipse.jface.wizard.WizardPage;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Text;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.custom.ScrolledComposite;


/**
 * @author Romano Simone 0512101343
 * This page show agent's step method description.
 */
public class L_StepMethodPage extends WizardPage{
	
	private static Logger log = Logger.getLogger("global");
	private AgentAnalizer agentAnalizer;
	private Composite container;
	private ScrolledComposite scrolledComposite;
	private Composite composite;
	private Text textMethodBody;
	private Text textUserDescription;
	private Label lblAutoGeneratedComment;
	private String pageDescription = "Who (i.e., what entity) does what, and in what order?\n";

	public L_StepMethodPage() {
		super("wizardPage");
		agentAnalizer = GlobalUtility.getAgentAnalizer();
		setTitle("3/7 - Process overview and scheduling\n" + agentAnalizer.getClassName());
		setDescription(pageDescription);		
	}
	
	public void createControl(Composite parent) {
		container = new Composite(parent, SWT.NULL);
		setControl(container);
		container.setLayout(new GridLayout(1,true));
		
		scrolledComposite = new ScrolledComposite(container, SWT.BORDER | SWT.H_SCROLL | SWT.V_SCROLL);
		GridData gd_scrolledComposite = new GridData(SWT.LEFT, SWT.CENTER, false, false, 1, 1);
		gd_scrolledComposite.heightHint = 256;
		gd_scrolledComposite.widthHint = 545;
		scrolledComposite.setLayoutData(gd_scrolledComposite);
		scrolledComposite.setExpandHorizontal(true);
		scrolledComposite.setExpandVertical(true);
		
		composite = new Composite(scrolledComposite, SWT.NONE);
		composite.setLayout(new GridLayout(1, false));
		
		textMethodBody = new Text(composite, SWT.BORDER | SWT.H_SCROLL | SWT.V_SCROLL | SWT.CANCEL | SWT.MULTI);
		GridData gd_textMethodBody = new GridData(SWT.FILL, SWT.CENTER, true, false, 1, 1);
		gd_textMethodBody.heightHint = 169;
		textMethodBody.setLayoutData(gd_textMethodBody);
		
	
		scrolledComposite.setContent(composite);
		scrolledComposite.setMinSize(composite.computeSize(SWT.DEFAULT, SWT.DEFAULT));
		myCreateControl();
	}
		
	@Override
	public boolean canFlipToNextPage() {
		return true;
	}

	public void myCreateControl() {
		setDescription("Information about step method of " + agentAnalizer.getClassName());
		Method step = GlobalUtility.getStepMethod();
		//**************************************//
		//adding label with autogenerated comment
		lblAutoGeneratedComment = new Label(composite, SWT.NONE);
		lblAutoGeneratedComment.setText(GlobalUtility.getStepMethodInformation(step));
		//**************************************//
		
		Label lblPutYourComment = new Label(composite, SWT.NONE);
		lblPutYourComment.setText("Your comment here:");
		
		textUserDescription = new Text(composite, SWT.BORDER | SWT.H_SCROLL | SWT.V_SCROLL | SWT.CANCEL | SWT.MULTI);
		GridData gd_textUserDescription = new GridData(SWT.FILL, SWT.CENTER, true, false, 1, 1);
		gd_textUserDescription.heightHint = 65;
		textUserDescription.setLayoutData(gd_textUserDescription);
		
		textMethodBody.setText(textMethodBody.getText() +  step.getMethod());		

		//getting old user input if exist//
		ProcessOverviewElement p = ODD.getProcessOverviewAndScheduling().getProcessOverviewElement(agentAnalizer.getClassName() + "step");
		if (p != null)
			if (p.getUserDoWhat() != null)
				textUserDescription.setText(p.getUserDoWhat());
		//******************************//
		
		scrolledComposite.setContent(composite);
		scrolledComposite.setMinSize(composite.computeSize(SWT.DEFAULT, SWT.DEFAULT));
	}

	public IWizardPage getNextPage(){ 
		//add start method information on method declaration
		Method step = GlobalUtility.getStepMethod();
		String commentValue = "@ingroup process\n*\n" + textUserDescription.getText() + "\n";
		commentValue = commentValue + lblAutoGeneratedComment.getText();
		GlobalUtility.setJavadocToMethod(agentAnalizer.getRoot(), step, commentValue);
		ODD.addProcessOverviewElement(agentAnalizer.getClassName() + "step", lblAutoGeneratedComment.getText(), textUserDescription.getText());
		//add agent page if project has agents
		if (GlobalUtility.getNextAgentAnalizer() != null){	//return next agent is exist
			L_StepMethodPage nextPage = new L_StepMethodPage();
			((MASONDocumentationWizard) super.getWizard()).addPage(nextPage);
			return nextPage;
		}
		else{
			M_DesignConceptsPage nextPage = new M_DesignConceptsPage();
			((MASONDocumentationWizard) super.getWizard()).addPage(nextPage);
			return nextPage;
		}
		
	}
}
